services:
  nextcloud_db:
    image: postgres:17
    hostname: nextcloud_db
    restart: always
    volumes:               
     - ./database:/var/lib/postgresql/data                   
    env_file: .env   
    networks:            
      - nextcloud_db      

  nextcloud_redis:
    hostname: nextcloud_redis
    image: redis:7.4
    restart: always
    networks:
      - nextcloud_db

  nextcloud_app:  
    hostname: nextcloud_app
    image: nextcloud:32
    restart: always
    depends_on:
      - nextcloud_db
    volumes:
      - ./data/www/html:/var/www/html
    networks:
      - nextcloud_db
      - frontend
    extra_hosts:
      - "nuage.$DOMAIN:172.18.0.1"  # adapter l'IP à ton réseau docker
      - "onlyoffice.$DOMAIN:172.18.0.1"  # adapter l'IP à ton réseau docker
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.nextcloud_$ROUTER_NAME.tls.certresolver=myresolver"
      - "traefik.http.routers.nextcloud_$ROUTER_NAME.rule=Host(`nuage.$DOMAIN`)"
      - "traefik.http.services.nextcloud_$ROUTER_NAME.loadbalancer.server.port=80"

      - "traefik.http.routers.nextcloud_$ROUTER_NAME.middlewares=nextcloud_custom_header_$ROUTER_NAME, nextcloud_redirectregex_$ROUTER_NAME, crowdsec@file"

        # Pour le chargement de scripts extérieurs, ex : onlyoffice
      - "traefik.http.middlewares.nextcloud_custom_header_$ROUTER_NAME.headers.customResponseHeaders.Strict-Transport-Security=max-age=15552000; includeSubDomains; preload;"
      - "traefik.http.middlewares.nextcloud_custom_header_$ROUTER_NAME.headers.contentSecurityPolicy=frame-ancestors 'self' ${DOMAIN} onlyoffice.${DOMAIN} "

        # redirection nécéssaire au desktop client et autres webdav
      - "traefik.http.middlewares.nextcloud_redirectregex_$ROUTER_NAME.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_redirectregex_$ROUTER_NAME.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirectregex_$ROUTER_NAME.redirectregex.replacement=https://$${1}/remote.php/dav"


networks:
  frontend:
    external: true
  nextcloud_db:
    internal: true